#!/bin/bash

CC= gcc -std=c99
CCFLAGS= -Wall -Werror -g
OPTIMIZE= -O3

SERVER= server
CLIENT= client
TARGET_SERVER= server.c
TARGET_CLIENT= client.c
GIT_HOOKS := .git/hooks/pre-commit
EXEC= target

ifeq ("$(VERBOSE)","1")
   Q :=
   VECHO = @true
else
   Q := @
   VECHO = @printf
endif


.PHONY: all
all: $(EXEC)

$(GIT_HOOKS):
	@scripts/install-git-hooks
	@echo

%.o: %.c
	$(VECHO) "  CC\t$@\n"
	$(Q)$(CC) -o $@ $(CFLAGS) -c -MMD -MF .$@.d $<


OBJS_LIB = \
	tst.o bloom.o

target:	$(OBJS_LIB)
	$(CC) -o $(SERVER) $(CCFLAGS) $(OPTIMIZE) $(TARGET_SERVER) -pthread
	$(CC) -o $(CLIENT) $(CCFLAGS) $(OPTIMIZE) $(TARGET_CLIENT) -pthread

debug:
	$(CC) -o $(SERVER) $(CCFLAGS) -g $(TARGET_SERVER) -pthread
	$(CC) -o $(CLIENT) $(CCFLAGS) -g $(TARGET_CLIENT) -pthread

prof:
	$(CC) -o $(SERVER) $(CCFLAGS) -g -pg $(TARGET_SERVER) -pthread
	$(CC) -o $(CLIENT) $(CCFLAGS) -g -pg $(TARGET_CLIENT) -pthread

clean:
	rm -rf $(SERVER)
	rm -rf $(CLIENT)
	rm -rf gmon.out
